# docker-compose.yml
version: '3.9'
services:
  db:
    image: postgres
    container_name: bugtracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: bugtracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
